### ISSUE TITLE
Зависимость на старую версию consta ui

### ISSUE THREAD

**Issue by 4adOFF** [gazprom-neft/consta-charts#25]
**Описание бага**
При выполнении npm install 

npm ERR! Could not resolve dependency:
npm ERR! peer @consta/uikit@"1.12.2" from @consta/charts@0.2.2
npm ERR! node_modules/@consta/charts
npm ERR!   @consta/charts@"^0.2.2" from the root project

npm версии 7.5.1

Не хотелось бы завязываться на уже старую версию @consta/uikit
В package.json в блок dependency содержит:
"@consta/charts": "^0.2.2",
"@consta/uikit": "^3.3.0"

**Comment by 4adOFF** [comment]
@gizeasy именно предупреждения и выдаются но только до 7 версии npm, для версий npm 7+ эти предупреждения считаются ошибкой

**Comment by Lyubavskaya** [comment]
исправлено в версии 0.3.0
