### ISSUE TITLE
Когда планируется введение компонента Mix?

### ISSUE THREAD

**Issue by 4adOFF** [gazprom-neft/consta-charts#6]
Речь о компоненте [Mix](https://g2plot.antv.vision/en/examples/case/customize#line) для создания смешанных кастомных графиков Mix from '@antv/g2plot'
тот же вопрос о [DualAxes](https://g2plot.antv.vision/en/examples/dual-axes/column-line#column-multi-line)

Добавление данных компонентов в библиотеку планируется? Если да то когда?

**Comment by gizeasy** [comment]
Вообще планируем перенести все графики к нам. Очередь добавления будет формироваться от запросов пользователя.

Если требуется прямо сейчас вы можете создать Пр по аналогии с другими компонентами, по факту там добаляется только тема, текущее апи можено не менять. В некоторых компонентах пробовал добавлять нормальную типизацию, в данном компоненте думаю это будет лишнее так как он слишком сложный, и достаточно будет просто накинуть в него тему.

DualAxes уже добавлен, в среду будет релиз

**Comment by 4adOFF** [comment]
На текущий момент хватит DualAxes, спасибо!
